pipeline {
    agent any
    environment {
    ANSIBLE_CONFIG='/var/lib/jenkins/jobs/config-mgt-ansible/branches/feature-project14.bumlt0/workspace/deployment/deploy/ansible.cfg'
    }
 parameters {
      string(name: 'inventory_file', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
      string(name: 'ansible_tag', defaultValue: '',  description: 'This is the tag to decide what role or playbook to run')
    }
	
stages {
    stage('SCM checkout') {
      steps {
       checkout([$class: 'GitSCM',
	  branches: [[name: '*/feature/project14']],
          userRemoteConfigs: [[url: 'https://github.com/sidahal2018/config-mgt-ansible.git']],
          extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'deployment']]])

      }
    }
	stage('Export ansible.cfg') {
      steps {
          sh 'export ANSIBLE_CONFIG=$ANSIBLE_CONFIG'
      }
    }
	
	
    stage('Execute Ansible') {
      steps {
          ansiblePlaybook credentialsId: 'private-key-tooling', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${params.inventory_file}', playbook: 'playbooks/site.yml'
      }
    }
    }
}
