pipeline {
    agent any


  stages {
    stage('SCM checkout') {
      steps {
          git 'https://github.com/sidahal2018/config-mgt-ansible.git'
      }
    }
	  stage('Execute Ansible') {
      steps {
          ansiblePlaybook disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
      }
    }
	
		
    }

}
