
 pipeline {
    agent any


  stages {
    stage('SCM checkout') {
      steps {
       checkout([$class: 'GitSCM',
	  branches: [[name: '*/feature/project14']],
          userRemoteConfigs: [[url: 'https://github.com/sidahal2018/config-mgt-ansible.git']],
          extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'deployment']]])

      }
    }
    stage('Execute Ansible') {
      steps {
          ansiblePlaybook credentialsId: 'private-key-tooling', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
      }
    }
    }
}

