---
# tasks file for webserver
- name: install packages
  include: installpkg.yml
- name: Set up Apache virtual Host
  include: configureapache.yml
- name: clone tooling website
  include: deploytooling.yml












