---
# tasks file for webserver
- name: install packages
  include: installpkg.yml
- name: Setup/confgigure httpd
  include: configureapache.yml
- name: clone tooling website
  include: deploytooling.yml












